# Generated by Django 3.2.13 on 2023-01-31 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='completion',
            field=models.ManyToManyField(blank=True, related_name='clear_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('role', models.ManyToManyField(related_name='situation', to='roadmaps.Role')),
            ],
        ),
    ]
