# Generated by Django 3.2.13 on 2023-02-03 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_roadmaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
