# Generated by Django 3.2.13 on 2023-02-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_auto_20230203_1300'),
        ('roadmaps', '0002_track_favorites'),
    ]

    operations = [
    ]
