# Generated by Django 3.2.13 on 2023-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0008_auto_20230116_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='completion',
            field=models.ManyToManyField(to='roadmaps.Track'),
        ),
        migrations.DeleteModel(
            name='Completion',
        ),
    ]
