# Generated by Django 3.2.13 on 2023-01-17 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadmaps', '0009_auto_20230117_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='completion',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
