# Generated by Django 3.2.13 on 2023-01-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0014_auto_20230125_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='role',
            field=models.ManyToManyField(related_name='situation', to='roadmaps.Role'),
        ),
    ]
