# Generated by Django 3.2.13 on 2023-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20230130_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/thumnail_default.png', null=True, upload_to=''),
        ),
    ]
