# Generated by Django 3.2.13 on 2023-01-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_article_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
