# Generated by Django 3.2.13 on 2023-01-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20230131_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletempimage',
            name='image',
            field=models.ImageField(upload_to='media/temp_images/'),
        ),
    ]
