# Generated by Django 3.2.13 on 2023-01-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_articletempimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletempimage',
            name='image',
            field=models.ImageField(upload_to='temp_images/'),
        ),
    ]
