# Generated by Django 3.2.13 on 2023-02-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_article_thumnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articletempimage',
            name='image',
            field=models.ImageField(upload_to='article/temp_images/'),
        ),
    ]
