# Generated by Django 3.2.13 on 2023-01-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_articleimage_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
