# Generated by Django 3.2.13 on 2023-02-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20230203_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumnail_image',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='article/thumnail.png', null=True, upload_to='article/thumbnail/'),
        ),
    ]
