# Generated by Django 3.2.13 on 2023-02-09 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('login_type', models.CharField(max_length=10)),
                ('sns_service_id', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('profile_image', models.ImageField(default='media/default.png', upload_to='')),
                ('introduce', models.TextField(blank=True, default='아직 자기소개가 없습니다.', null=True)),
                ('login_type', models.CharField(max_length=10, null=True)),
                ('stat', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('svc_use_pcy_agmt_yn', models.BooleanField(default=False, null=True)),
                ('ps_info_proc_agmt_yn', models.BooleanField(default=False, null=True)),
                ('mkt_info_recv_agmt_yn', models.BooleanField(default=False, null=True)),
                ('news_feed_push_yn', models.BooleanField(default=False, null=True)),
                ('noti_push_yn', models.BooleanField(default=False, null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
