# Generated by Django 3.2.13 on 2023-02-08 11:57

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='mkt_info_recv_agmt_yn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='news_feed_push_yn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='noti_push_yn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ps_info_proc_agmt_yn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='svc_use_pcy_agmt_yn',
        ),
    ]
