# Generated by Django 3.2.13 on 2023-02-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mkt_info_recv_agmt_yn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='news_feed_push_yn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='noti_push_yn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ps_info_proc_agmt_yn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='svc_use_pcy_agmt_yn',
        ),
        migrations.AddField(
            model_name='user',
            name='sns_service_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
