# Generated by Django 3.2.13 on 2023-02-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230207_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stat',
        ),
    ]
