# Generated by Django 3.2.13 on 2023-02-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_type',
        ),
    ]
